//GCC
// mobiflight.h
// Not required by Arduino IDE, added to allow compilation through a conventional IDE (CodeBlocks)

void attachCommandCallbacks(void);;
void OnResetBoard(void);;
void setup(void);;
void generateSerial(bool force);;
void loadConfig(void);;
void _storeConfig(void);;
void SetPowerSavingMode(bool state);
void updatePowerSaving(void);
void loop(void);
bool isPinRegistered(byte pin);
//bool isPinRegisteredForType(byte pin, byte type);
//void registerPin(byte pin, byte type);
void registerPin(byte pin);
void clearRegisteredPins(void);
void clearRegisteredPins(byte type);
void AddOutput(uint8_t pin = 1, String name = "Output");
void ClearOutputs(void);
void AddButton(uint8_t pin = 1, String name = "Button");
void ClearButtons(void);
void AddEncoder(uint8_t pin1 = 1, uint8_t pin2 = 2, String name = "Encoder");
void ClearEncoders(void);
void AddLedSegment(int dataPin, int csPin, int clkPin, int numDevices, int brightness);
void ClearLedSegments(void);
void PowerSaveLedSegment(bool state);
void AddStepper(int pin1, int pin2, int pin3, int pin4, int btnPin1);
void ClearSteppers(void);
void AddServo(int pin);
void ClearServos(void);
void AddLcdDisplay (uint8_t address = 0x24, uint8_t cols = 16, uint8_t lines = 2, String name = "LCD");
void ClearLcdDisplays(void);
void handlerOnRelease(byte eventId, uint8_t pin, String name);
void handlerOnEncoder(byte eventId, uint8_t pin, String name);
void OnSetConfig(void);
void resetConfig(void);
void OnResetConfig(void);
void OnSaveConfig(void);
void OnActivateConfig(void);
void _activateConfig(void);
void readConfig(String cfg);
void OnUnknownCommand(void);
void OnGetInfo(void);
void OnGetConfig(void);
void OnSetPin(void);
void OnInitModule(void);
void OnSetModule(void);
void OnSetStepper(void);
void OnResetStepper(void);
void OnSetZeroStepper(void);
void OnSetServo(void);
void OnSetLcdDisplayI2C(void);
void updateSteppers(void);
void updateServos(void);
void readButtons(void);
void readEncoder(void);
void OnGenNewSerial(void);
void OnSetName(void);
void _storeName(void);
void _restoreName(void);
void OnTrigger(void);
